dist/Net-Ping - Update to version 2.77
From Changes:

2.77  2026-06-02 07:34:55 rurban
      Minor
      - Fix tests to about.com (GH #34)
      - Replace broken cpm matrix tests with cpanm

diff --git a/dist/Net-Ping/Makefile.PL b/dist/Net-Ping/Makefile.PL
--- a/dist/Net-Ping/Makefile.PL
+++ b/dist/Net-Ping/Makefile.PL
@@ -30,11 +30,11 @@ push @extras,
         resources   => {
             # TODO: 26 old issues still open at RT
             # https://rt.cpan.org/Public/Dist/Display.html?Name=Net-Ping
-            bugtracker  => 'https://github.com/Perl/perl5/issues',
+            bugtracker  => 'https://github.com/rurban/Net-Ping/issues',
             repository  => {
                 type => 'git',
-                url => 'https://github.com/Perl/perl5.git',
-                web => 'https://github.com/Perl/perl5',
+                url => 'https://github.com/rurban/Net-Ping.git',
+                web => 'https://github.com/rurban/Net-Ping',
             },
             license     => [ 'http://dev.perl.org/licenses/' ],
         },
@@ -55,7 +55,7 @@ WriteMakefile(
     'Test::Pod'           => '1.22',
     'Test::More'          => 0,
   },
-  INSTALLDIRS => ( $] < 5.011 ? 'perl' : 'site' ),
+  INSTALLDIRS => ($ENV{PERL_CORE} ? 'perl' : 'site'),
   clean      => { FILES => 'Net-Ping-*' },
   @extras
 );
@@ -67,7 +67,13 @@ sub depend {
 README : lib/Net/Ping.pm
 	pod2text lib/Net/Ping.pm > README
 release : dist
-	git tag \$(VERSION)
+	if test \"\$(shell git rev-parse --abbrev-ref HEAD)\" != \"master\" || \\
+           test \"\$(shell git diff --raw)\" != \"\" || \\
+           test \"\$(shell git diff --cached --raw)\" != \"\" ; then \\
+          echo 'You are not on a clean master branch, aborting.'; \\
+          exit 1; \\
+	fi
+	-git tag -f \$(VERSION)
 	cpan-upload \$(DISTVNAME).tar\$(SUFFIX)
 	git push
 	git push --tags
