Integrate: [ 27520] Remove unused code. No extension use Makefile.SH any more.
[ 27521]
Change 27520 was a bit too aggressive.  Let's keep the warning.

[ 27693]
The make_ext script should pass MAKE=$MAKE to submakes it invokes for
extentions, as they in turn may invoke $MAKE, and should invoke the
same $MAKE as at the top level, which may not be $Config{make}
p4raw-link: @27693 on //depot/perl: 1c8b6db8160546df62c753cdbb48e3f8553b7af0
p4raw-link: @27521 on //depot/perl: 4b4bd025b2297f15aadaf5a5249fa56096be11a0
p4raw-link: @27520 on //depot/perl: ca68a6e02855e0cd3c7f33d87d015a1b8500f124

p4raw-id: //depot/maint-5.8/perl@30338
p4raw-integrated: from //depot/perl@30337 'copy in' ext/util/make_ext
	(@27549..)

diff --git a/ext/util/make_ext b/ext/util/make_ext
--- a/ext/util/make_ext
+++ b/ext/util/make_ext
@@ -123,12 +123,7 @@ if test ! -f $makefile ; then
 	test -f Makefile.PL && ../$depth/miniperl -I../$depth/lib Makefile.PL INSTALLDIRS=perl PERL_CORE=1 $passthru
 fi
 if test ! -f $makefile ; then
-	if test -f Makefile.SH; then
-		echo "Warning: Writing $makefile from old-style Makefile.SH!"
-		sh Makefile.SH
-	else
-		echo "Warning: No Makefile!"
-	fi
+	echo "Warning: No Makefile!"
 fi
 
 case "$target" in
@@ -136,10 +131,10 @@ clean)		;;
 realclean)	;;
 *)	# Give makefile an opportunity to rewrite itself.
 	# reassure users that life goes on...
-	$MAKE config $passthru || echo "$MAKE config failed, continuing anyway..."
+	$MAKE config MAKE=$MAKE $passthru || echo "$MAKE config failed, continuing anyway..."
 	;;
 esac
 
-$MAKE $makeopts $target $makeargs $passthru || exit
+$MAKE $makeopts $target MAKE=$MAKE $makeargs $passthru || exit
 
 exit $?
