Configure, sysroot: failing to guess usrinc needn't be fatal
Previously, if we failed to guess usrinc, incpth, or libpth and were
cross-compiling, Configure would've bailed out immediately.  This commit
makes it more lenient if using -Dsysroot; in case of failure it will now
warn, but Configure will continue as usual; this is because the defaults
for those variables will now use sysroot, so they have a higher chance
of being accurate.

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -4715,7 +4715,13 @@ case "$ccname" in
                 *)  echo "Using usrinc $usrinc." >&4 ;;
             esac
             case "$croak" in
-                y) echo "Cannot continue, aborting." >&4; exit 1 ;;
+                y) 
+                if test "X$sysroot" = X; then
+                    echo "Cannot continue, aborting." >&4; exit 1
+                else
+                    echo "Cross-compiling using sysroot $sysroot, failing to guess inc/lib paths is not fatal" >&4
+                fi
+                ;;
             esac
             ;;
         esac
