integrate changes#6376..6378,6380,6383,6385..6388,6391
       Cosmetics and perldelta.

       Fix nits noticed by Boston.pm.

       Do the cc sanity check both before the hints and
       after the cc selction.

       get sprintf.t to adjust properly for 3-digit exponents

       don't clobber *.orig files on *clean targets

       fix bugs in processing %v-*d and similar format specs (from
       Avi Finkel <avi@finkel.org>)

       sprintf test tweaks (from Dominic Dunlop)

       new selfloader.t in change#6183 doesn't close DATA handles,
       and thus fails to clean up tmp files on dosish platforms

       typos (spotted by Peter Prymmer)

       typo fix from Craig Berry

p4raw-link: @6385 on //depot/perl: bb2899ba824e18be66f3ca9d67696457ff235d98
p4raw-link: @6383 on //depot/perl: 56acea6ff1302cdf8b9d387cd3766c26e5146dca
p4raw-link: @6380 on //depot/perl: 48237ddebcafead6ccafb1124390a1ce30560e1f
p4raw-link: @6378 on //depot/metaconfig: 5d6e559bed8131ab89b0913a90bbeebc924a451bon //depot/cfgperl: 2573c5f9376c426c078dbe90cdebc1d347ddc348
p4raw-link: @6376 on //depot/metaconfig: b8372171f570ef8413673058be4226bef77ffce2on //depot/cfgperl: 70e8c5e4f67dde6bf07eb296d727a29b95fe8b5b
p4raw-link: @6183 on //depot/perl: bfdd149997f4a56ec34c947f0d733ecbfb53a519

p4raw-id: //depot/maint-5.6/perl@7779
p4raw-integrated: from //depot/cfgperl@7778 'copy in'
	vms/subconfigure.com (@6168..) pod/perlre.pod (@6192..)
p4raw-integrated: from //depot/cfgperl@6378 'edit in' Configure
	config_h.SH (@6376..)
p4raw-integrated: from //depot/cfgperl@6376 'merge in'
	pod/perldelta.pod (@6339..)
p4raw-integrated: from //depot/perl@6388 'edit in' Configure (@6381..)
	'merge in' t/lib/english.t (@6352..)
p4raw-integrated: from //depot/perl@6387 'copy in' t/lib/selfloader.t
	(@6183..)
p4raw-integrated: from //depot/perl@6386 'edit in' t/op/sprintf.t
	(@6385..)
p4raw-integrated: from //depot/perl@6385 'merge in' sv.c (@6373..)
p4raw-integrated: from //depot/perl@6383 'copy in'
	ext/IPC/SysV/Makefile.PL (@1967..) x2p/Makefile.SH (@3774..)
	Makefile.SH (@6369..)

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -20,7 +20,7 @@
 
 # $Id: Head.U,v 3.0.1.9 1997/02/28 15:02:09 ram Exp $
 #
-# Generated on Tue Jun 27 04:45:48 EET DST 2000 [metaconfig 3.0 PL70]
+# Generated on Wed Jul 12 07:59:35 EET DST 2000 [metaconfig 3.0 PL70]
 # (with additional metaconfig patches by perlbug@perl.com)
 
 cat >/tmp/c1$$ <<EOF
@@ -2032,6 +2032,62 @@ FOO
 	;;
 esac
 
+cat <<EOS >checkcc
+$startsh
+EOS
+cat <<'EOSC' >>checkcc
+case "$cc" in
+'') ;;
+*)  $rm -f try try.*
+    $cat >try.c <<EOM
+int main(int argc, char *argv[]) {
+  return 0;
+}
+EOM
+    if $cc -o try try.c; then
+       :
+    else
+        echo "Uh-oh, the C compiler '$cc' doesn't seem to be working." >&4
+        despair=yes
+        trygcc=yes
+        case "$cc" in
+        *gcc*) trygcc=no ;;
+        esac
+        case "`$cc -v -c try.c 2>&1`" in
+        *gcc*) trygcc=no ;;
+        esac
+        if $test X"$trygcc" = Xyes; then
+            if gcc -o try -c try.c; then
+                echo " "
+                echo "You seem to have a working gcc, though." >&4
+                rp="Would you like to use it?"
+                dflt=y
+                if $test -f myread; then
+                    . ./myread
+                else
+                    if $test -f UU/myread; then
+                        . ./UU/myread
+                    else
+                        echo "Cannot find myread, sorry.  Aborting." >&2
+                        exit 1
+                    fi
+                fi  
+                case "$ans" in
+                [yY]*) cc=gcc; ccflags=''; despair=no ;;
+                esac
+            fi
+        fi
+        if $test X"$despair" = Xyes; then
+            echo "You need to find a working C compiler." >&4
+            echo "I cannot continue any further, aborting." >&4
+            exit 1
+        fi
+    fi
+    $rm -f try try.*
+    ;;
+esac
+EOSC
+
 : determine whether symbolic links are supported
 echo " "
 $touch blurfl
@@ -2164,6 +2220,7 @@ if test -f config.sh; then
 		;;
 	esac
 fi
+. ./UU/checkcc
 if test ! -f config.sh; then
 	$cat <<EOM
 
@@ -3079,46 +3136,7 @@ fi
 if $test -f cc.cbu; then
     . ./cc.cbu
 fi
-: Quick sanity check, we will do a fuller one later when we know
-: the various flags and libs
-$rm -f try try.*
-$cat >try.c <<EOM
-int main(int argc, char *argv[]) {
-  return 0;
-}
-EOM
-if $cc -o try try.c; then
-   :
-else
-   echo "Uh-oh, the C compiler "$cc" doesn't seem to be working..." >&4
-   despair=yes
-   trygcc=yes
-   case "$cc" in
-   *gcc) trygcc=no ;;
-   esac
-   case "`$cc -v 2>&1`" in
-   *gcc*) trygcc=no ;;
-   esac
-   if $test X"$trygcc" = Xyes; then
-      if gcc -o try try.c; then
-        echo " "
-        echo "You seem to have a working gcc, though."
-        rp="Do you want to use it?"
-        dflt=y
-        . ./myread
-        case "$ans" in
-        [yY]*) cc=gcc; despair=no ;;
-        esac
-      fi
-   fi
-   if $test X"$despair" = Xyes; then
-      echo "You need to find a working C compiler." >&4
-      echo "I cannot continue any further, aborting." >&4
-      exit 1
-   fi
-fi
-$rm -f try try.*
-
+. ./checkcc
 
 echo " "
 echo "Checking for GNU cc in disguise and/or its version number..." >&4
@@ -9738,7 +9756,7 @@ echo 'int main() { long long x = 7; return 0; }' > try.c
 set try
 if eval $compile; then
 	val="$define"
-	echo "You have have long long."
+	echo "You have long long."
 else
 	val="$undef"
 	echo "You do not have long long."
