Remove Configure code that supported the old-style nested layout for ext/
5.10.1 switched to the new layout, so this code would only be useful for
backporting to maint-5.8. That isn't going happen, so it can go.

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -22372,51 +22372,34 @@ find_extensions='
 	    DynaLoader|dynaload) ;;
 	    *)
 	    this_ext=`echo $xxx | $sed -e s/-/\\\//g`;
-	    leaf=`echo $xxx | $sed -e s/.*-//`;
-	    if $test -d File; then
-		if $test -f $xxx/$leaf.xs -o -f $xxx/$leaf.c; then
-		    known_extensions="$known_extensions $1$this_ext";
-		elif $test -f $xxx/Makefile.PL; then
-		    nonxs_extensions="$nonxs_extensions $1$this_ext";
-		else
-		    if $test -d $xxx -a $# -lt 10; then
-			set $1$xxx/ $*;
-			cd "$xxx";
-			eval $find_extensions;
-			cd ..;
-			shift;
-		    fi;
-		fi;
-	    else
-		echo " $known_extensions $nonxs_extensions" > $$.tmp;
-		if $contains " $this_ext " $$.tmp; then
-		    echo >&4;
-		    echo "Duplicate directories detected for extension $xxx" >&4;
-		    echo "Configure cannot correctly recover from this - shall I abort?" >&4;
-		    case "$knowitall" in
-		    "") dflt=y;;
-		    *) dflt=n;;
-		    esac;
-		    . ../UU/myread;
-		    case "$ans" in
-		    n*|N*) ;;
-		    *) echo >&4;
-		       echo "Ok.  Stopping Configure." >&4;
-		       echo "Please remove the duplicate directory (e.g. using git clean) and then re-run Configure" >&4;
-			exit 1;;
-		    esac;
-		    echo "Ok.  You will need to correct config.sh before running make." >&4;
-		fi;
-		$ls -1 $xxx > $$.tmp;
-		if   $contains "\.xs$" $$.tmp > /dev/null 2>&1; then
-		    known_extensions="$known_extensions $this_ext";
-		elif $contains "\.c$"  $$.tmp > /dev/null 2>&1; then
-		    known_extensions="$known_extensions $this_ext";
-		elif $test -d $xxx; then
-		    nonxs_extensions="$nonxs_extensions $this_ext";
-		fi;
-		$rm -f $$.tmp;
-	    fi
+	    echo " $known_extensions $nonxs_extensions" > $$.tmp;
+	    if $contains " $this_ext " $$.tmp; then
+		echo >&4;
+		echo "Duplicate directories detected for extension $xxx" >&4;
+		echo "Configure cannot correctly recover from this - shall I abort?" >&4;
+		case "$knowitall" in
+		"") dflt=y;;
+		*) dflt=n;;
+		esac;
+		. ../UU/myread;
+		case "$ans" in
+		n*|N*) ;;
+		*) echo >&4;
+		    echo "Ok.  Stopping Configure." >&4;
+		    echo "Please remove the duplicate directory (e.g. using git clean) and then re-run Configure" >&4;
+		    exit 1;;
+		esac;
+		echo "Ok.  You will need to correct config.sh before running make." >&4;
+	    fi;
+	    $ls -1 $xxx > $$.tmp;
+	    if   $contains "\.xs$" $$.tmp > /dev/null 2>&1; then
+		known_extensions="$known_extensions $this_ext";
+	    elif $contains "\.c$"  $$.tmp > /dev/null 2>&1; then
+		known_extensions="$known_extensions $this_ext";
+	    elif $test -d $xxx; then
+		nonxs_extensions="$nonxs_extensions $this_ext";
+	    fi;
+	    $rm -f $$.tmp;
 	    ;;
 	esac;
     done'
@@ -22433,16 +22416,6 @@ cd "$rsrc/ext"
 set X
 shift
 eval $find_extensions
-if $test -d File-Glob; then
-    : All ext/ flattened
-else
-    # Special case:  Add in modules that nest beyond the first level.
-    # Currently threads/shared and Hash/Util/FieldHash, since they are
-    # not picked up by the recursive find above (and adding in general
-    # recursive finding breaks SDBM_File/sdbm).
-    # A.D. 20011025 (SDBM), ajgough 20071008 (FieldHash)
-    known_extensions="$known_extensions threads/shared Hash/Util/FieldHash"
-fi
 set X $known_extensions
 shift
 known_extensions=`echo "$*" | tr ' ' $trnl | $sort | tr $trnl ' '`
