Integrate: [ 33547] Final move from meta-3.0 to meta-3.5
[ 33589]
Make uudmap.h dependencies more explicit in the VMS build
(needed by MMS but not MMK).

[ 33597]
Add i_syspoll to all the pre-canned configs.

[ 33598]
Subject: [PATCH] Re: Smoke [5.11.0] 33456 PASS darwin 9.2.0 (macppcG5/1 cpu)
From: Dominic Dunlop <shouldbedomo@mac.com>
Message-Id: <3B7752C8-D5A2-452C-B3E0-C453FFCBCAFA@mac.com>
Date: Tue, 11 Mar 2008 21:54:04 +0100

[but rename ******* to i_mallocmalloc.U, and then fix up all the files
that Porting/checkcfgvar.pl says need i_mallocmalloc declared]

[ 33606]
Subject: detecting Configure test goofs (Was Re: branch prediction hints)
From: Nicholas Clark <nick@ccl4.org>
Date: Mon, 24 Mar 2008 16:35:09 +0000
Message-ID: <20080324163509.GW79799@plum.flirble.org>
p4raw-link: @33606 on //depot/perl: 08593cf4c9cb1d67bbda4d67054ff396110647f9
p4raw-link: @33598 on //depot/perl: 1cd66f7c5bbf47a0c9c6f45b3eae3670bbe447db
p4raw-link: @33597 on //depot/perl: 3420cd608b369be387bfc5e65cad34a2bf659561
p4raw-link: @33589 on //depot/perl: b50d78f710e31d33fee2acc5e8cfddc61da1eb9b
p4raw-link: @33547 on //depot/perl: 216dac0429f7f2def8388be78bca5dd81baf8702

p4raw-id: //depot/maint-5.10/perl@33894
p4raw-integrated: from //depot/perl@33893 'copy in' configure.com
	(@33591..) plan9/config_sh.sample (@33597..) 'edit in'
	Cross/config.sh-arm-linux epoc/config.sh (@33597..) 'merge in'
	vms/descrip_mms.template (@32649..)
p4raw-integrated: from //depot/perl@33606 'copy in' Configure
	(@33598..)
p4raw-integrated: from //depot/perl@33598 'copy in' config_h.SH
	(@33547..) 'merge in' perl.h (@33448..)
p4raw-integrated: from //depot/perl@33597 'edit in' Porting/config.sh
	(@33049..) 'ignore' NetWare/config.wc symbian/config.sh
	uconfig.sh win32/config.ce (@33049..) win32/config.bc
	(@33345..) win32/config.gc win32/config.vc win32/config.vc64
	(@33347..)
p4raw-integrated: from //depot/perl@33547 'ignore' Porting/Glossary
	(@33321..)

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -25,7 +25,7 @@
 
 # $Id: Head.U 6 2006-08-25 22:21:46Z rmanfredi $
 #
-# Generated on Fri Feb 15 17:37:37 CET 2008 [metaconfig 3.0 PL70]
+# Generated on Sun Mar 30 11:17:56 CEST 2008 [metaconfig 3.5 PL0]
 # (with additional metaconfig patches by perlbug@perl.org)
 
 cat >c1$$ <<EOF
@@ -869,6 +869,7 @@ i_limits=''
 i_locale=''
 i_machcthr=''
 i_malloc=''
+i_mallocmalloc=''
 i_math=''
 i_memory=''
 i_mntent=''
@@ -912,6 +913,7 @@ i_sysmode=''
 i_sysmount=''
 i_sysndir=''
 i_sysparam=''
+i_syspoll=''
 i_sysresrc=''
 i_syssecrt=''
 i_sysselct=''
@@ -1646,7 +1648,7 @@ while test $# -gt 0; do
 	    esac
 	    shift
 	    ;;
-	-V) echo "$me generated by metaconfig 3.0 PL70." >&2
+	-V) echo "$me generated by metaconfig 3.5 PL0." >&2
 	    exit 0;;
 	--) break;;
 	-*) echo "$me: unknown option $1" >&2; shift; error=true;;
@@ -4012,7 +4014,7 @@ y) td=$was; tu=$was;;
 esac
 EOSC
 
-: function used to set $1 to $val
+: function used to set '$1' to '$val'
 setvar='var=$1; eval "was=\$$1"; td=$define; tu=$undef;
 case "$val$was" in
 $define$undef) . ./whoa; eval "$var=\$td";;
@@ -5380,6 +5382,11 @@ $rm_try gcctest gcctest.out
 compile='
 mc_file=$1;
 shift;
+case "$usedevel" in $define|true|[yY]*) if $test ! -f "${mc_file}.c"; then
+echo "Internal Configure script bug - compiler test file ${mc_file}.c is missing. Please report this to perlbug@perl.org" >&4;
+exit 1;
+fi;
+esac;
 $cc -o ${mc_file} $optimize $ccflags $ldflags $* ${mc_file}.c $libs > /dev/null 2>&1;'
 : define a shorthand compile call for compilations that should be ok.
 compile_ok='
@@ -6549,6 +6556,10 @@ case "$inc_version_list" in
 esac
 $rm -f getverlist
 
+: see if malloc/malloc.h has to be included
+set malloc/malloc.h i_mallocmalloc
+eval $inhdr
+
 : see if this is a malloc.h system
 : we want a real compile instead of Inhdr because some systems have a
 : malloc.h that just gives a compile error saying to use stdlib.h instead
@@ -6556,6 +6567,11 @@ echo " "
 $cat >try.c <<EOCP
 #include <stdlib.h>
 #include <malloc.h>
+$i_mallocmalloc I_MALLOCMALLOC
+#ifdef I_MALLOCMALLOC
+# include <malloc/malloc.h>
+#endif
+
 int main () { return 0; }
 EOCP
 set try
@@ -12273,6 +12289,24 @@ set d_open3
 eval $setvar
 $rm_try
 
+: script used to emit important warnings
+cat >warn <<EOS
+$startsh
+if test \$# -gt 0; then
+	echo "\$@" >msg
+else
+	cat >msg
+fi
+echo "*** WARNING:" >&4
+sed -e 's/^/*** /' <msg >&4
+echo "*** " >&4
+cat msg >>config.msg
+echo " " >>config.msg
+rm -f msg
+EOS
+chmod +x warn
+$eunicefix warn
+
 : see which of string.h or strings.h is needed
 echo " "
 strings=`./findhdr string.h`
@@ -12285,7 +12319,7 @@ else
 	if $test "$strings" && $test -r "$strings"; then
 		echo "Using <strings.h> instead of <string.h>." >&4
 	else
-		echo "No string header found -- You'll surely have problems." >&4
+		./warn "No string header found -- You'll surely have problems."
 	fi
 fi
 set i_string
@@ -19631,6 +19665,7 @@ esac
 set mad
 eval $setvar
 
+: check whether make sets MAKE
 echo " "
 echo "Checking if your $make program sets \$(MAKE)..." >&4
 case "$make_set_make" in
@@ -21084,14 +21119,14 @@ case "$val3" in
 				echo "<sgtty.h> found." >&4
 			else
 				echo "System is pyramid with BSD universe."
-				echo "<sgtty.h> not found--you could have problems." >&4
+				./warn "<sgtty.h> not found--you could have problems."
 			fi;;
 		*) if $test `./findhdr termio.h`; then
 				val="$define"
 				echo "<termio.h> found." >&4
 			else
 				echo "System is pyramid with USG universe."
-				echo "<termio.h> not found--you could have problems." >&4
+				./warn "<termio.h> not found--you could have problems."
 			fi;;
 		esac
 	elif ./usg; then
@@ -21102,7 +21137,7 @@ case "$val3" in
 			echo "<sgtty.h> found." >&4
 			val2="$define"
 		else
-echo "Neither <termio.h> nor <sgtty.h> found--you could have problems." >&4
+			./warn "Neither <termio.h> nor <sgtty.h> found--cross fingers!"
 		fi
 	else
 		if $test `./findhdr sgtty.h`; then
@@ -21112,7 +21147,7 @@ echo "Neither <termio.h> nor <sgtty.h> found--you could have problems." >&4
 			echo "<termio.h> found." >&4
 			val="$define"
 		else
-echo "Neither <sgtty.h> nor <termio.h> found--you could have problems." >&4
+			./warn "Neither <sgtty.h> nor <termio.h> found--cross fingers!"
 		fi
 	fi;;
 esac
@@ -21175,6 +21210,10 @@ eval $inhdr
 
 : see if this is a sys/mode.h system
 set sys/mode.h i_sysmode
+eval $inhdr
+
+: see if there is a sys/poll.h file
+set sys/poll.h i_syspoll
 eval $inhdr
 
 : see if sys/resource.h has to be included
@@ -22329,6 +22368,7 @@ i_limits='$i_limits'
 i_locale='$i_locale'
 i_machcthr='$i_machcthr'
 i_malloc='$i_malloc'
+i_mallocmalloc='$i_mallocmalloc'
 i_math='$i_math'
 i_memory='$i_memory'
 i_mntent='$i_mntent'
@@ -22363,6 +22403,7 @@ i_sysmode='$i_sysmode'
 i_sysmount='$i_sysmount'
 i_sysndir='$i_sysndir'
 i_sysparam='$i_sysparam'
+i_syspoll='$i_syspoll'
 i_sysresrc='$i_sysresrc'
 i_syssecrt='$i_syssecrt'
 i_sysselct='$i_sysselct'
