Configure: bail out when neither stdarg.h nor varargs.h
Perl uses variadic functions, so we need at least one of the relevant
mechanisms available; for this reason, the CompCert C compiler is unsuitable
for our purposes.

If the person building Perl wants to carry on regardless, they can use the
"-K" option.

This partly addresses RT#112494.

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -10882,6 +10882,7 @@ chmod +x varargs
 : now check which varargs header should be included
 echo " "
 i_varhdr=''
+val=""
 case "$valstd" in
 "$define")
 	if `./varargs I_STDARG`; then
@@ -10898,6 +10899,15 @@ case "$valstd" in
 esac
 case "$val" in
 '')
+	echo " "
+	echo "*** WHOA THERE!!! ***" >&4
+	echo "    Your C compiler \"$cc\" doesn't seem to support stdarg or varargs!" >&4
+	case "$knowitall" in
+	'')
+	echo "    I'm giving up; maybe you can try again with a different compiler?" >&4
+		exit 1
+		;;
+	esac
 echo "I could not find the definition for va_dcl... You have problems..." >&4
 	val="$undef"; set i_stdarg; eval $setvar
 	val="$undef"; set i_varargs; eval $setvar
