Final move from meta-3.0 to meta-3.5
p4raw-id: //depot/perl@33547

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -25,7 +25,7 @@
 
 # $Id: Head.U 6 2006-08-25 22:21:46Z rmanfredi $
 #
-# Generated on Fri Feb 15 17:37:37 CET 2008 [metaconfig 3.0 PL70]
+# Generated on Fri Mar 21 11:25:23 CET 2008 [metaconfig 3.5 PL0]
 # (with additional metaconfig patches by perlbug@perl.org)
 
 cat >c1$$ <<EOF
@@ -912,6 +912,7 @@ i_sysmode=''
 i_sysmount=''
 i_sysndir=''
 i_sysparam=''
+i_syspoll=''
 i_sysresrc=''
 i_syssecrt=''
 i_sysselct=''
@@ -1646,7 +1647,7 @@ while test $# -gt 0; do
 	    esac
 	    shift
 	    ;;
-	-V) echo "$me generated by metaconfig 3.0 PL70." >&2
+	-V) echo "$me generated by metaconfig 3.5 PL0." >&2
 	    exit 0;;
 	--) break;;
 	-*) echo "$me: unknown option $1" >&2; shift; error=true;;
@@ -4012,7 +4013,7 @@ y) td=$was; tu=$was;;
 esac
 EOSC
 
-: function used to set $1 to $val
+: function used to set '$1' to '$val'
 setvar='var=$1; eval "was=\$$1"; td=$define; tu=$undef;
 case "$val$was" in
 $define$undef) . ./whoa; eval "$var=\$td";;
@@ -12271,6 +12272,24 @@ set d_open3
 eval $setvar
 $rm_try
 
+: script used to emit important warnings
+cat >warn <<EOS
+$startsh
+if test \$# -gt 0; then
+	echo "\$@" >msg
+else
+	cat >msg
+fi
+echo "*** WARNING:" >&4
+sed -e 's/^/*** /' <msg >&4
+echo "*** " >&4
+cat msg >>config.msg
+echo " " >>config.msg
+rm -f msg
+EOS
+chmod +x warn
+$eunicefix warn
+
 : see which of string.h or strings.h is needed
 echo " "
 strings=`./findhdr string.h`
@@ -12283,7 +12302,7 @@ else
 	if $test "$strings" && $test -r "$strings"; then
 		echo "Using <strings.h> instead of <string.h>." >&4
 	else
-		echo "No string header found -- You'll surely have problems." >&4
+		./warn "No string header found -- You'll surely have problems."
 	fi
 fi
 set i_string
@@ -19629,6 +19648,7 @@ esac
 set mad
 eval $setvar
 
+: check whether make sets MAKE
 echo " "
 echo "Checking if your $make program sets \$(MAKE)..." >&4
 case "$make_set_make" in
@@ -21082,14 +21102,14 @@ case "$val3" in
 				echo "<sgtty.h> found." >&4
 			else
 				echo "System is pyramid with BSD universe."
-				echo "<sgtty.h> not found--you could have problems." >&4
+				./warn "<sgtty.h> not found--you could have problems."
 			fi;;
 		*) if $test `./findhdr termio.h`; then
 				val="$define"
 				echo "<termio.h> found." >&4
 			else
 				echo "System is pyramid with USG universe."
-				echo "<termio.h> not found--you could have problems." >&4
+				./warn "<termio.h> not found--you could have problems."
 			fi;;
 		esac
 	elif ./usg; then
@@ -21100,7 +21120,7 @@ case "$val3" in
 			echo "<sgtty.h> found." >&4
 			val2="$define"
 		else
-echo "Neither <termio.h> nor <sgtty.h> found--you could have problems." >&4
+			./warn "Neither <termio.h> nor <sgtty.h> found--cross fingers!"
 		fi
 	else
 		if $test `./findhdr sgtty.h`; then
@@ -21110,7 +21130,7 @@ echo "Neither <termio.h> nor <sgtty.h> found--you could have problems." >&4
 			echo "<termio.h> found." >&4
 			val="$define"
 		else
-echo "Neither <sgtty.h> nor <termio.h> found--you could have problems." >&4
+			./warn "Neither <sgtty.h> nor <termio.h> found--cross fingers!"
 		fi
 	fi;;
 esac
@@ -21173,6 +21193,10 @@ eval $inhdr
 
 : see if this is a sys/mode.h system
 set sys/mode.h i_sysmode
+eval $inhdr
+
+: see if there is a sys/poll.h file
+set sys/poll.h i_syspoll
 eval $inhdr
 
 : see if sys/resource.h has to be included
@@ -22361,6 +22385,7 @@ i_sysmode='$i_sysmode'
 i_sysmount='$i_sysmount'
 i_sysndir='$i_sysndir'
 i_sysparam='$i_sysparam'
+i_syspoll='$i_syspoll'
 i_sysresrc='$i_sysresrc'
 i_syssecrt='$i_syssecrt'
 i_sysselct='$i_sysselct'
