Integrate changes #8099,8218,8220,8221,8227,8304,8317, 8318,8320,8337,8503,8877,8890,8903,8971 from mainline to maintperl.
Subject: Re: [ID 20000328.039] [PATCH] Eliminate Configure use of /tmp

Add Configure option -Dmksymlinks which will create a symlink
forest if the current/build differs from the source directory.
(8218,8220,8221,8317,8318,8971)

Subject: Re: A Configure option like 'otherlibdirs' but for *pre*pending?
(Document APPLLIB_EXP in INSTALL.)

If running byacc write-enable also perly.h.

DB3 NDBM/ODBM emulation tweaks from Stanislav Brabec <utx@penguin.cz>.

Subject: [PATCH 5.7.1/Configure] failure to set src='.'

Sanity check for conflicting thread flavours.

Fix the sys/fcntl.h problem reported by Peter Prymmer.

Add few CPUs/architectures to the Cppsym scan,
add -perlio to archname if so selected (modified 8890)

Be more helpful for devel builders, suggested by John L. Allen.
(admittedly pointless change for maintperl, but the usedevel
 code is there already)

p4raw-link: @8227 on //depot/perl: a61357a9a84c55ce0c74b8d2bbfb23900cb5bd17
p4raw-link: @8221 on //depot/perl: 4b661809a7c66d2c579a3f04c11e70664742d63e
p4raw-link: @8220 on //depot/perl: 4ba7095c8b1e78642662b76b43ac3fa8cbda5537
p4raw-link: @8218 on //depot/perl: dafca956013a09f7b5201b464199f47cf100f00f
p4raw-link: @8099 on //depot/perl: 283fdd21d4eecddd8bb08913a0759c5db0de7645

p4raw-id: //depot/maint-5.6/perl@8995
p4raw-integrated: from //depot/perl@8993 'copy in'
	ext/NDBM_File/NDBM_File.xs (@5091..) ext/ODBM_File/ODBM_File.xs
	(@5117..) INSTALL (@8227..) 'edit in' Configure (@8890..)
	'ignore' config_h.SH (@8888..) 'merge in' warnings.pl (@8029..)
	embed.pl (@8934..)
p4raw-integrated: from //depot/perl@8304 'edit in' Makefile.SH
	(@8220..)
p4raw-integrated: from //depot/perl@8221 'merge in' epoc/config.sh
	win32/config.bc win32/config.gc win32/config.vc (@8138..)
	Porting/Glossary Porting/config.sh Porting/config_H (@8198..)
p4raw-integrated: from //depot/perl@8220 'merge in' t/io/fs.t (@6874..)

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -20,10 +20,10 @@
 
 # $Id: Head.U,v 3.0.1.9 1997/02/28 15:02:09 ram Exp $
 #
-# Generated on Wed Feb 21 16:35:15 EET 2001 [metaconfig 3.0 PL70]
+# Generated on Wed Feb 21 17:01:28 EET 2001 [metaconfig 3.0 PL70]
 # (with additional metaconfig patches by perlbug@perl.org)
 
-cat >/tmp/c1$$ <<EOF
+cat >c1$$ <<EOF
 ARGGGHHHH!!!!!
 
 SCO csh still thinks true is false.  Write to SCO today and tell them that next
@@ -34,18 +34,18 @@ we'd have to do is go in and swap the && and || tokens, wherever they are.)
 
 [End of diatribe. We now return you to your regularly scheduled programming...]
 EOF
-cat >/tmp/c2$$ <<EOF
+cat >c2$$ <<EOF
 
 OOPS!  You naughty creature!  You didn't run Configure with sh!
 I will attempt to remedy the situation by running sh for you...
 EOF
 
-true || cat /tmp/c1$$ /tmp/c2$$
+true || cat c1$$ c2$$
 true || exec sh $0 $argv:q
 
-(exit $?0) || cat /tmp/c2$$
+(exit $?0) || cat c2$$
 (exit $?0) || exec sh $0 $argv:q
-rm -f /tmp/c1$$ /tmp/c2$$
+rm -f c1$$ c2$$
 
 : compute my invocation name
 me=$0
@@ -721,6 +721,7 @@ installusrbinperl=''
 intsize=''
 longsize=''
 shortsize=''
+issymlink=''
 libc=''
 ldlibpthname=''
 libperl=''
@@ -1433,6 +1434,7 @@ case "$src" in
     */*) src=`echo $0 | sed -e 's%/[^/][^/]*$%%'`
          case "$src" in
 	 /*)	;;
+	 .)	;;
          *)	src=`cd ../$src && pwd` ;;
 	 esac
          ;;
@@ -1798,6 +1800,9 @@ $define|true|[yY]*) ;;
     It is most seriously suggested that you do not continue any further
     unless you want to help in developing and debugging Perl.
 
+    If you *still* want to build perl, you can answer 'y' now,
+    or pass -Dusedevel to Configure.
+
 EOH
 	rp='Do you really want to continue?'
 	dflt='n'
@@ -2061,6 +2066,7 @@ test)
 *)
 	if `sh -c "PATH= test true" >/dev/null 2>&1`; then
 		echo "Using the test built into your sh."
+		echo "Using the test built into your sh."
 		test=test
 		_test=test
 	fi
@@ -2168,6 +2174,93 @@ else
 	lns="$ln"
 fi
 $rm -f blurfl sym
+
+: determine whether symbolic links are supported
+echo " "
+case "$lns" in
+*"ln -s")
+	echo "Checking how to test for symbolic links..." >&4
+	$lns blurfl sym
+	if $test "X$issymlink" = X; then
+		sh -c "PATH= test -h sym" >/dev/null 2>&1
+		if test $? = 0; then
+			issymlink="test -h"
+		fi		
+	fi
+	if $test "X$issymlink" = X; then
+		if  $test -h >/dev/null 2>&1; then
+			issymlink="$test -h"
+			echo "Your builtin 'test -h' may be broken, I'm using external '$test -h'." >&4
+		fi		
+	fi
+	if $test "X$issymlink" = X; then
+		if $test -L sym 2>/dev/null; then
+			issymlink="$test -L"
+		fi
+	fi
+	if $test "X$issymlink" != X; then
+		echo "You can test for symbolic links with '$issymlink'." >&4
+	else
+		echo "I do not know how you can test for symbolic links." >&4
+	fi
+	$rm -f blurfl sym
+	;;
+*)	echo "No symbolic links, so not testing for their testing..." >&4
+	;;
+esac
+echo " "
+
+
+case "$mksymlinks" in
+$define|true|[yY]*)
+	case "$src" in
+	''|'.')	echo "Cannot create symlinks in the original directory." >&4
+		exit 1
+		;;
+	*)	case "$lns:$issymlink" in
+		*"ln -s:-"?)
+			echo "Creating the symbolic links..." >&4
+			echo "(First creating the subdirectories...)" >&4
+			cd ..
+			awk '{print $1}' $src/MANIFEST | grep / | sed 's:/[^/]*$::' | sort -u | while true; do
+				read directory
+				test -z "$directory" && break
+				mkdir -p $directory
+			done
+			# Sanity check 1.
+			if test ! -d t/base; then
+				echo "Failed to create the subdirectories.  Aborting." >&4
+				exit 1
+			fi
+			echo "(Then creating the symlinks...)" >&4
+			awk '{print $1}' $src/MANIFEST | while true; do
+				read filename
+				test -z "$filename" && break
+				if test -f $filename; then
+					if $issymlink $filename; then
+						rm -f $filename
+					fi
+				fi
+				if test -f $filename; then
+					echo "$filename already exists, not symlinking."
+				else
+					ln -s $src/$filename $filename
+				fi
+			done
+			# Sanity check 2.
+			if test ! -f t/base/commonsense.t; then
+				echo "Failed to create the symlinks.  Aborting." >&4
+				exit 1
+			fi
+			cd UU
+			;;
+		*)	echo "(I cannot figure out how to do symbolic links, ignoring mksymlinks)." >&4
+			;;
+		esac
+		;;
+	esac
+	;;
+esac
 
 : see whether [:lower:] and [:upper:] are supported character classes
 echo " "
@@ -2837,6 +2930,19 @@ EOM
 	;;
 *)
 	useithreads="$undef"
+	use5005threads="$undef"
+	;;
+esac
+
+case "$useithreads$use5005threads" in
+"$define$define")
+	$cat >&4 <<EOM
+
+You cannot have both the ithreads and the 5.005 threads enabled
+at the same time.  Disabling the 5.005 threads since they are
+much less stable than the ithreads.
+
+EOM
 	use5005threads="$undef"
 	;;
 esac
@@ -4049,8 +4155,8 @@ and I got the following output:
 
 EOM
 dflt=y
-if sh -c "$cc -o try $optimize $ccflags $ldflags try.c $libs" >>try.msg 2>&1; then
-	if sh -c './try' >>try.msg 2>&1; then
+if $sh -c "$cc -o try $optimize $ccflags $ldflags try.c $libs" >>try.msg 2>&1; then
+	if $sh -c './try' >>try.msg 2>&1; then
 		xxx=`./try`
 		case "$xxx" in
 		"Ok") dflt=n ;;
@@ -5260,6 +5366,18 @@ $define)
 	        esac
 		;;
 	esac
+	;;
+esac
+case "$useperlio" in
+$define)
+	echo "Perlio selected." >&4
+	case "$archname" in
+        *-perlio*) echo "...and architecture name already has -perlio." >&4
+                ;;
+        *)      archname="$archname-perlio"
+                echo "...setting architecture name to $archname." >&4
+                ;;
+        esac
 	;;
 esac
 
@@ -8748,6 +8866,8 @@ int main()
 #ifdef F_SETFL
 		if (-1 == fcntl(pd[0], F_SETFL, MY_O_NONBLOCK))
 			exit(1);
+#else
+		exit(4);
 #endif
 		signal(SIGALRM, blech);
 		alarm(5);
@@ -8795,6 +8915,7 @@ EOCP
 		1) echo "Could not perform non-blocking setting!";;
 		2) echo "I did a successful read() for something that was not there!";;
 		3) echo "Hmm... non-blocking I/O does not seem to be working!";;
+		4) echo "Could not find F_SETFL!";;
 		*) echo "Something terribly wrong happened during testing.";;
 		esac
 		rd_nodata=`$cat try.ret`
@@ -14688,9 +14809,9 @@ $echo "Guessing which symbols your C compiler and preprocessor define..." >&4
 $cat <<'EOSH' > Cppsym.know
 a29k ABI64 aegis AES_SOURCE AIX AIX32 AIX370
 AIX41 AIX42 AIX43 AIX_SOURCE aixpc ALL_SOURCE
-alliant alpha am29000 AM29000 amiga AMIGAOS AMIX
-ansi ANSI_C_SOURCE apollo ardent atarist att386 att3b BeOS
-BIG_ENDIAN BIT_MSF bsd BSD bsd43 bsd4_2 bsd4_3 BSD4_3 bsd4_4
+alliant alpha am29000 AM29000 AMD64 amiga AMIGAOS AMIX
+ansi ANSI_C_SOURCE apollo ardent ARM32 atarist att386 att3b
+BeOS BIG_ENDIAN BIT_MSF bsd BSD bsd43 bsd4_2 bsd4_3 BSD4_3 bsd4_4
 BSD_4_3 BSD_4_4 BSD_NET2 BSD_TIME BSD_TYPES BSDCOMPAT bsdi
 bull c cadmus clipper CMU COFF COMPILER_VERSION
 concurrent convex cpu cray CRAY CRAYMPP ctix CX_UX
@@ -14703,7 +14824,7 @@ hp200 hp300 hp700 HP700 hp800 hp9000
 hp9000s200 hp9000s300 hp9000s400 hp9000s500
 hp9000s700 hp9000s800 hp9k8 hp_osf hppa hpux HPUX_SOURCE
 i186 i286 i386 i486 i586 i686 i8086 i80960 i860 I960
-iAPX286 ibm ibm032 ibmesa IBMR2 ibmrt ILP32 ILP64
+IA64 iAPX286 ibm ibm032 ibmesa IBMR2 ibmrt ILP32 ILP64
 INLINE_INTRINSICS INTRINSICS INT64 interdata is68k ksr1
 LANGUAGE_C LARGE_FILE_API LARGEFILE64_SOURCE
 LARGEFILE_SOURCE LFS64_LARGEFILE LFS_LARGEFILE
@@ -14727,7 +14848,7 @@ pc532 pdp11 PGC PIC plexus PORTAR posix
 POSIX1B_SOURCE POSIX2_SOURCE POSIX4_SOURCE
 POSIX_C_SOURCE POSIX_SOURCE POWER
 PROTOTYPES PWB pyr QNX R3000 REENTRANT RES Rhapsody RISC6000
-riscix riscos RT scs SCO sequent sgi SGI_SOURCE sinix
+riscix riscos RT S390 SA110 scs SCO sequent sgi SGI_SOURCE SH3 sinix
 SIZE_INT SIZE_LONG SIZE_PTR SOCKET_SOURCE SOCKETS_SOURCE
 sony sony_news sonyrisc sparc sparclite spectrum
 stardent stdc STDC_EXT stratos sun sun3 sun386
@@ -14735,6 +14856,7 @@ Sun386i svr3 svr4 SVR4_2 SVR4_SOURCE svr5
 SX system SYSTYPE_BSD SYSTYPE_BSD43 SYSTYPE_BSD44
 SYSTYPE_SVR4 SYSTYPE_SVR5 SYSTYPE_SYSV SYSV SYSV3 SYSV4 SYSV5
 sysV68 sysV88 Tek4132 Tek4300 titan
+TM3200 TM5400 TM5600
 tower tower32 tower32_200 tower32_600 tower32_700
 tower32_800 tower32_850 tss
 u370 u3b u3b2 u3b20 u3b200 u3b20d u3b5
@@ -16024,6 +16146,7 @@ installvendorarch='$installvendorarch'
 installvendorbin='$installvendorbin'
 installvendorlib='$installvendorlib'
 intsize='$intsize'
+issymlink='$issymlink'
 ivdformat='$ivdformat'
 ivsize='$ivsize'
 ivtype='$ivtype'
